[package]
name = "input_event_codes_proc_macro"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
quote = "1.0"
bindgen = "0.59"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
syn = { version = "1.0", features = [ "full", "parsing" ] }

[lib]
proc-macro = true
