[package]
name = "generator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
quote = "1.0"
bindgen = "0.59"
proc-macro2 = "1.0"
syn = { version = "1.0", features = [ "full", "parsing" ] }

