// This file is generated.
//
// Do NOT edit this file, instead modify the generator.

#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Abs(u32);
impl Abs {
    pub const fn new(value: u32) -> Abs {
        Abs(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Abs {
    fn from(value: u32) -> Abs {
        Abs(value)
    }
}
impl From<Abs> for u32 {
    fn from(value: Abs) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Abs {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Abs {
    #[doc(alias = "ABS_X")]
    pub const X: Abs = Abs(0);
    #[doc(alias = "ABS_Y")]
    pub const Y: Abs = Abs(1);
    #[doc(alias = "ABS_Z")]
    pub const Z: Abs = Abs(2);
    #[doc(alias = "ABS_RX")]
    pub const RX: Abs = Abs(3);
    #[doc(alias = "ABS_RY")]
    pub const RY: Abs = Abs(4);
    #[doc(alias = "ABS_RZ")]
    pub const RZ: Abs = Abs(5);
    #[doc(alias = "ABS_THROTTLE")]
    pub const THROTTLE: Abs = Abs(6);
    #[doc(alias = "ABS_RUDDER")]
    pub const RUDDER: Abs = Abs(7);
    #[doc(alias = "ABS_WHEEL")]
    pub const WHEEL: Abs = Abs(8);
    #[doc(alias = "ABS_GAS")]
    pub const GAS: Abs = Abs(9);
    #[doc(alias = "ABS_BRAKE")]
    pub const BRAKE: Abs = Abs(10);
    #[doc(alias = "ABS_HAT0X")]
    pub const HAT0X: Abs = Abs(16);
    #[doc(alias = "ABS_HAT0Y")]
    pub const HAT0Y: Abs = Abs(17);
    #[doc(alias = "ABS_HAT1X")]
    pub const HAT1X: Abs = Abs(18);
    #[doc(alias = "ABS_HAT1Y")]
    pub const HAT1Y: Abs = Abs(19);
    #[doc(alias = "ABS_HAT2X")]
    pub const HAT2X: Abs = Abs(20);
    #[doc(alias = "ABS_HAT2Y")]
    pub const HAT2Y: Abs = Abs(21);
    #[doc(alias = "ABS_HAT3X")]
    pub const HAT3X: Abs = Abs(22);
    #[doc(alias = "ABS_HAT3Y")]
    pub const HAT3Y: Abs = Abs(23);
    #[doc(alias = "ABS_PRESSURE")]
    pub const PRESSURE: Abs = Abs(24);
    #[doc(alias = "ABS_DISTANCE")]
    pub const DISTANCE: Abs = Abs(25);
    #[doc(alias = "ABS_TILT_X")]
    pub const TILT_X: Abs = Abs(26);
    #[doc(alias = "ABS_TILT_Y")]
    pub const TILT_Y: Abs = Abs(27);
    #[doc(alias = "ABS_TOOL_WIDTH")]
    pub const TOOL_WIDTH: Abs = Abs(28);
    #[doc(alias = "ABS_VOLUME")]
    pub const VOLUME: Abs = Abs(32);
    #[doc(alias = "ABS_MISC")]
    pub const MISC: Abs = Abs(40);
    #[doc(alias = "ABS_RESERVED")]
    pub const RESERVED: Abs = Abs(46);
    #[doc(alias = "ABS_MT_SLOT")]
    pub const MT_SLOT: Abs = Abs(47);
    #[doc(alias = "ABS_MT_TOUCH_MAJOR")]
    pub const MT_TOUCH_MAJOR: Abs = Abs(48);
    #[doc(alias = "ABS_MT_TOUCH_MINOR")]
    pub const MT_TOUCH_MINOR: Abs = Abs(49);
    #[doc(alias = "ABS_MT_WIDTH_MAJOR")]
    pub const MT_WIDTH_MAJOR: Abs = Abs(50);
    #[doc(alias = "ABS_MT_WIDTH_MINOR")]
    pub const MT_WIDTH_MINOR: Abs = Abs(51);
    #[doc(alias = "ABS_MT_ORIENTATION")]
    pub const MT_ORIENTATION: Abs = Abs(52);
    #[doc(alias = "ABS_MT_POSITION_X")]
    pub const MT_POSITION_X: Abs = Abs(53);
    #[doc(alias = "ABS_MT_POSITION_Y")]
    pub const MT_POSITION_Y: Abs = Abs(54);
    #[doc(alias = "ABS_MT_TOOL_TYPE")]
    pub const MT_TOOL_TYPE: Abs = Abs(55);
    #[doc(alias = "ABS_MT_BLOB_ID")]
    pub const MT_BLOB_ID: Abs = Abs(56);
    #[doc(alias = "ABS_MT_TRACKING_ID")]
    pub const MT_TRACKING_ID: Abs = Abs(57);
    #[doc(alias = "ABS_MT_PRESSURE")]
    pub const MT_PRESSURE: Abs = Abs(58);
    #[doc(alias = "ABS_MT_DISTANCE")]
    pub const MT_DISTANCE: Abs = Abs(59);
    #[doc(alias = "ABS_MT_TOOL_X")]
    pub const MT_TOOL_X: Abs = Abs(60);
    #[doc(alias = "ABS_MT_TOOL_Y")]
    pub const MT_TOOL_Y: Abs = Abs(61);
    #[doc(alias = "ABS_MAX")]
    pub const MAX: Abs = Abs(63);
    #[doc(alias = "ABS_CNT")]
    pub const CNT: Abs = Abs(64);
}
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Btn(u32);
impl Btn {
    pub const fn new(value: u32) -> Btn {
        Btn(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Btn {
    fn from(value: u32) -> Btn {
        Btn(value)
    }
}
impl From<Btn> for u32 {
    fn from(value: Btn) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Btn {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Btn {
    #[doc(alias = "BTN_MISC")]
    pub const MISC: Btn = Btn(256);
    #[doc(alias = "BTN_0")]
    pub const _0: Btn = Btn(256);
    #[doc(alias = "BTN_1")]
    pub const _1: Btn = Btn(257);
    #[doc(alias = "BTN_2")]
    pub const _2: Btn = Btn(258);
    #[doc(alias = "BTN_3")]
    pub const _3: Btn = Btn(259);
    #[doc(alias = "BTN_4")]
    pub const _4: Btn = Btn(260);
    #[doc(alias = "BTN_5")]
    pub const _5: Btn = Btn(261);
    #[doc(alias = "BTN_6")]
    pub const _6: Btn = Btn(262);
    #[doc(alias = "BTN_7")]
    pub const _7: Btn = Btn(263);
    #[doc(alias = "BTN_8")]
    pub const _8: Btn = Btn(264);
    #[doc(alias = "BTN_9")]
    pub const _9: Btn = Btn(265);
    #[doc(alias = "BTN_MOUSE")]
    pub const MOUSE: Btn = Btn(272);
    #[doc(alias = "BTN_LEFT")]
    pub const LEFT: Btn = Btn(272);
    #[doc(alias = "BTN_RIGHT")]
    pub const RIGHT: Btn = Btn(273);
    #[doc(alias = "BTN_MIDDLE")]
    pub const MIDDLE: Btn = Btn(274);
    #[doc(alias = "BTN_SIDE")]
    pub const SIDE: Btn = Btn(275);
    #[doc(alias = "BTN_EXTRA")]
    pub const EXTRA: Btn = Btn(276);
    #[doc(alias = "BTN_FORWARD")]
    pub const FORWARD: Btn = Btn(277);
    #[doc(alias = "BTN_BACK")]
    pub const BACK: Btn = Btn(278);
    #[doc(alias = "BTN_TASK")]
    pub const TASK: Btn = Btn(279);
    #[doc(alias = "BTN_JOYSTICK")]
    pub const JOYSTICK: Btn = Btn(288);
    #[doc(alias = "BTN_TRIGGER")]
    pub const TRIGGER: Btn = Btn(288);
    #[doc(alias = "BTN_THUMB")]
    pub const THUMB: Btn = Btn(289);
    #[doc(alias = "BTN_THUMB2")]
    pub const THUMB2: Btn = Btn(290);
    #[doc(alias = "BTN_TOP")]
    pub const TOP: Btn = Btn(291);
    #[doc(alias = "BTN_TOP2")]
    pub const TOP2: Btn = Btn(292);
    #[doc(alias = "BTN_PINKIE")]
    pub const PINKIE: Btn = Btn(293);
    #[doc(alias = "BTN_BASE")]
    pub const BASE: Btn = Btn(294);
    #[doc(alias = "BTN_BASE2")]
    pub const BASE2: Btn = Btn(295);
    #[doc(alias = "BTN_BASE3")]
    pub const BASE3: Btn = Btn(296);
    #[doc(alias = "BTN_BASE4")]
    pub const BASE4: Btn = Btn(297);
    #[doc(alias = "BTN_BASE5")]
    pub const BASE5: Btn = Btn(298);
    #[doc(alias = "BTN_BASE6")]
    pub const BASE6: Btn = Btn(299);
    #[doc(alias = "BTN_DEAD")]
    pub const DEAD: Btn = Btn(303);
    #[doc(alias = "BTN_GAMEPAD")]
    pub const GAMEPAD: Btn = Btn(304);
    #[doc(alias = "BTN_SOUTH")]
    pub const SOUTH: Btn = Btn(304);
    #[doc(alias = "BTN_A")]
    pub const A: Btn = Btn(304);
    #[doc(alias = "BTN_EAST")]
    pub const EAST: Btn = Btn(305);
    #[doc(alias = "BTN_B")]
    pub const B: Btn = Btn(305);
    #[doc(alias = "BTN_C")]
    pub const C: Btn = Btn(306);
    #[doc(alias = "BTN_NORTH")]
    pub const NORTH: Btn = Btn(307);
    #[doc(alias = "BTN_X")]
    pub const X: Btn = Btn(307);
    #[doc(alias = "BTN_WEST")]
    pub const WEST: Btn = Btn(308);
    #[doc(alias = "BTN_Y")]
    pub const Y: Btn = Btn(308);
    #[doc(alias = "BTN_Z")]
    pub const Z: Btn = Btn(309);
    #[doc(alias = "BTN_TL")]
    pub const TL: Btn = Btn(310);
    #[doc(alias = "BTN_TR")]
    pub const TR: Btn = Btn(311);
    #[doc(alias = "BTN_TL2")]
    pub const TL2: Btn = Btn(312);
    #[doc(alias = "BTN_TR2")]
    pub const TR2: Btn = Btn(313);
    #[doc(alias = "BTN_SELECT")]
    pub const SELECT: Btn = Btn(314);
    #[doc(alias = "BTN_START")]
    pub const START: Btn = Btn(315);
    #[doc(alias = "BTN_MODE")]
    pub const MODE: Btn = Btn(316);
    #[doc(alias = "BTN_THUMBL")]
    pub const THUMBL: Btn = Btn(317);
    #[doc(alias = "BTN_THUMBR")]
    pub const THUMBR: Btn = Btn(318);
    #[doc(alias = "BTN_DIGI")]
    pub const DIGI: Btn = Btn(320);
    #[doc(alias = "BTN_TOOL_PEN")]
    pub const TOOL_PEN: Btn = Btn(320);
    #[doc(alias = "BTN_TOOL_RUBBER")]
    pub const TOOL_RUBBER: Btn = Btn(321);
    #[doc(alias = "BTN_TOOL_BRUSH")]
    pub const TOOL_BRUSH: Btn = Btn(322);
    #[doc(alias = "BTN_TOOL_PENCIL")]
    pub const TOOL_PENCIL: Btn = Btn(323);
    #[doc(alias = "BTN_TOOL_AIRBRUSH")]
    pub const TOOL_AIRBRUSH: Btn = Btn(324);
    #[doc(alias = "BTN_TOOL_FINGER")]
    pub const TOOL_FINGER: Btn = Btn(325);
    #[doc(alias = "BTN_TOOL_MOUSE")]
    pub const TOOL_MOUSE: Btn = Btn(326);
    #[doc(alias = "BTN_TOOL_LENS")]
    pub const TOOL_LENS: Btn = Btn(327);
    #[doc(alias = "BTN_TOOL_QUINTTAP")]
    pub const TOOL_QUINTTAP: Btn = Btn(328);
    #[doc(alias = "BTN_STYLUS3")]
    pub const STYLUS3: Btn = Btn(329);
    #[doc(alias = "BTN_TOUCH")]
    pub const TOUCH: Btn = Btn(330);
    #[doc(alias = "BTN_STYLUS")]
    pub const STYLUS: Btn = Btn(331);
    #[doc(alias = "BTN_STYLUS2")]
    pub const STYLUS2: Btn = Btn(332);
    #[doc(alias = "BTN_TOOL_DOUBLETAP")]
    pub const TOOL_DOUBLETAP: Btn = Btn(333);
    #[doc(alias = "BTN_TOOL_TRIPLETAP")]
    pub const TOOL_TRIPLETAP: Btn = Btn(334);
    #[doc(alias = "BTN_TOOL_QUADTAP")]
    pub const TOOL_QUADTAP: Btn = Btn(335);
    #[doc(alias = "BTN_WHEEL")]
    pub const WHEEL: Btn = Btn(336);
    #[doc(alias = "BTN_GEAR_DOWN")]
    pub const GEAR_DOWN: Btn = Btn(336);
    #[doc(alias = "BTN_GEAR_UP")]
    pub const GEAR_UP: Btn = Btn(337);
    #[doc(alias = "BTN_DPAD_UP")]
    pub const DPAD_UP: Btn = Btn(544);
    #[doc(alias = "BTN_DPAD_DOWN")]
    pub const DPAD_DOWN: Btn = Btn(545);
    #[doc(alias = "BTN_DPAD_LEFT")]
    pub const DPAD_LEFT: Btn = Btn(546);
    #[doc(alias = "BTN_DPAD_RIGHT")]
    pub const DPAD_RIGHT: Btn = Btn(547);
    #[doc(alias = "BTN_TRIGGER_HAPPY")]
    pub const TRIGGER_HAPPY: Btn = Btn(704);
    #[doc(alias = "BTN_TRIGGER_HAPPY1")]
    pub const TRIGGER_HAPPY1: Btn = Btn(704);
    #[doc(alias = "BTN_TRIGGER_HAPPY2")]
    pub const TRIGGER_HAPPY2: Btn = Btn(705);
    #[doc(alias = "BTN_TRIGGER_HAPPY3")]
    pub const TRIGGER_HAPPY3: Btn = Btn(706);
    #[doc(alias = "BTN_TRIGGER_HAPPY4")]
    pub const TRIGGER_HAPPY4: Btn = Btn(707);
    #[doc(alias = "BTN_TRIGGER_HAPPY5")]
    pub const TRIGGER_HAPPY5: Btn = Btn(708);
    #[doc(alias = "BTN_TRIGGER_HAPPY6")]
    pub const TRIGGER_HAPPY6: Btn = Btn(709);
    #[doc(alias = "BTN_TRIGGER_HAPPY7")]
    pub const TRIGGER_HAPPY7: Btn = Btn(710);
    #[doc(alias = "BTN_TRIGGER_HAPPY8")]
    pub const TRIGGER_HAPPY8: Btn = Btn(711);
    #[doc(alias = "BTN_TRIGGER_HAPPY9")]
    pub const TRIGGER_HAPPY9: Btn = Btn(712);
    #[doc(alias = "BTN_TRIGGER_HAPPY10")]
    pub const TRIGGER_HAPPY10: Btn = Btn(713);
    #[doc(alias = "BTN_TRIGGER_HAPPY11")]
    pub const TRIGGER_HAPPY11: Btn = Btn(714);
    #[doc(alias = "BTN_TRIGGER_HAPPY12")]
    pub const TRIGGER_HAPPY12: Btn = Btn(715);
    #[doc(alias = "BTN_TRIGGER_HAPPY13")]
    pub const TRIGGER_HAPPY13: Btn = Btn(716);
    #[doc(alias = "BTN_TRIGGER_HAPPY14")]
    pub const TRIGGER_HAPPY14: Btn = Btn(717);
    #[doc(alias = "BTN_TRIGGER_HAPPY15")]
    pub const TRIGGER_HAPPY15: Btn = Btn(718);
    #[doc(alias = "BTN_TRIGGER_HAPPY16")]
    pub const TRIGGER_HAPPY16: Btn = Btn(719);
    #[doc(alias = "BTN_TRIGGER_HAPPY17")]
    pub const TRIGGER_HAPPY17: Btn = Btn(720);
    #[doc(alias = "BTN_TRIGGER_HAPPY18")]
    pub const TRIGGER_HAPPY18: Btn = Btn(721);
    #[doc(alias = "BTN_TRIGGER_HAPPY19")]
    pub const TRIGGER_HAPPY19: Btn = Btn(722);
    #[doc(alias = "BTN_TRIGGER_HAPPY20")]
    pub const TRIGGER_HAPPY20: Btn = Btn(723);
    #[doc(alias = "BTN_TRIGGER_HAPPY21")]
    pub const TRIGGER_HAPPY21: Btn = Btn(724);
    #[doc(alias = "BTN_TRIGGER_HAPPY22")]
    pub const TRIGGER_HAPPY22: Btn = Btn(725);
    #[doc(alias = "BTN_TRIGGER_HAPPY23")]
    pub const TRIGGER_HAPPY23: Btn = Btn(726);
    #[doc(alias = "BTN_TRIGGER_HAPPY24")]
    pub const TRIGGER_HAPPY24: Btn = Btn(727);
    #[doc(alias = "BTN_TRIGGER_HAPPY25")]
    pub const TRIGGER_HAPPY25: Btn = Btn(728);
    #[doc(alias = "BTN_TRIGGER_HAPPY26")]
    pub const TRIGGER_HAPPY26: Btn = Btn(729);
    #[doc(alias = "BTN_TRIGGER_HAPPY27")]
    pub const TRIGGER_HAPPY27: Btn = Btn(730);
    #[doc(alias = "BTN_TRIGGER_HAPPY28")]
    pub const TRIGGER_HAPPY28: Btn = Btn(731);
    #[doc(alias = "BTN_TRIGGER_HAPPY29")]
    pub const TRIGGER_HAPPY29: Btn = Btn(732);
    #[doc(alias = "BTN_TRIGGER_HAPPY30")]
    pub const TRIGGER_HAPPY30: Btn = Btn(733);
    #[doc(alias = "BTN_TRIGGER_HAPPY31")]
    pub const TRIGGER_HAPPY31: Btn = Btn(734);
    #[doc(alias = "BTN_TRIGGER_HAPPY32")]
    pub const TRIGGER_HAPPY32: Btn = Btn(735);
    #[doc(alias = "BTN_TRIGGER_HAPPY33")]
    pub const TRIGGER_HAPPY33: Btn = Btn(736);
    #[doc(alias = "BTN_TRIGGER_HAPPY34")]
    pub const TRIGGER_HAPPY34: Btn = Btn(737);
    #[doc(alias = "BTN_TRIGGER_HAPPY35")]
    pub const TRIGGER_HAPPY35: Btn = Btn(738);
    #[doc(alias = "BTN_TRIGGER_HAPPY36")]
    pub const TRIGGER_HAPPY36: Btn = Btn(739);
    #[doc(alias = "BTN_TRIGGER_HAPPY37")]
    pub const TRIGGER_HAPPY37: Btn = Btn(740);
    #[doc(alias = "BTN_TRIGGER_HAPPY38")]
    pub const TRIGGER_HAPPY38: Btn = Btn(741);
    #[doc(alias = "BTN_TRIGGER_HAPPY39")]
    pub const TRIGGER_HAPPY39: Btn = Btn(742);
    #[doc(alias = "BTN_TRIGGER_HAPPY40")]
    pub const TRIGGER_HAPPY40: Btn = Btn(743);
}
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Ev(u32);
impl Ev {
    pub const fn new(value: u32) -> Ev {
        Ev(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Ev {
    fn from(value: u32) -> Ev {
        Ev(value)
    }
}
impl From<Ev> for u32 {
    fn from(value: Ev) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Ev {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Ev {
    #[doc(alias = "EV_SYN")]
    pub const SYN: Ev = Ev(0);
    #[doc(alias = "EV_KEY")]
    pub const KEY: Ev = Ev(1);
    #[doc(alias = "EV_REL")]
    pub const REL: Ev = Ev(2);
    #[doc(alias = "EV_ABS")]
    pub const ABS: Ev = Ev(3);
    #[doc(alias = "EV_MSC")]
    pub const MSC: Ev = Ev(4);
    #[doc(alias = "EV_SW")]
    pub const SW: Ev = Ev(5);
    #[doc(alias = "EV_LED")]
    pub const LED: Ev = Ev(17);
    #[doc(alias = "EV_SND")]
    pub const SND: Ev = Ev(18);
    #[doc(alias = "EV_REP")]
    pub const REP: Ev = Ev(20);
    #[doc(alias = "EV_FF")]
    pub const FF: Ev = Ev(21);
    #[doc(alias = "EV_PWR")]
    pub const PWR: Ev = Ev(22);
    #[doc(alias = "EV_FF_STATUS")]
    pub const FF_STATUS: Ev = Ev(23);
    #[doc(alias = "EV_MAX")]
    pub const MAX: Ev = Ev(31);
    #[doc(alias = "EV_CNT")]
    pub const CNT: Ev = Ev(32);
}
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Input(u32);
impl Input {
    pub const fn new(value: u32) -> Input {
        Input(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Input {
    fn from(value: u32) -> Input {
        Input(value)
    }
}
impl From<Input> for u32 {
    fn from(value: Input) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Input {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Input {
    #[doc(alias = "INPUT_PROP_POINTER")]
    pub const PROP_POINTER: Input = Input(0);
    #[doc(alias = "INPUT_PROP_DIRECT")]
    pub const PROP_DIRECT: Input = Input(1);
    #[doc(alias = "INPUT_PROP_BUTTONPAD")]
    pub const PROP_BUTTONPAD: Input = Input(2);
    #[doc(alias = "INPUT_PROP_SEMI_MT")]
    pub const PROP_SEMI_MT: Input = Input(3);
    #[doc(alias = "INPUT_PROP_TOPBUTTONPAD")]
    pub const PROP_TOPBUTTONPAD: Input = Input(4);
    #[doc(alias = "INPUT_PROP_POINTING_STICK")]
    pub const PROP_POINTING_STICK: Input = Input(5);
    #[doc(alias = "INPUT_PROP_ACCELEROMETER")]
    pub const PROP_ACCELEROMETER: Input = Input(6);
    #[doc(alias = "INPUT_PROP_MAX")]
    pub const PROP_MAX: Input = Input(31);
    #[doc(alias = "INPUT_PROP_CNT")]
    pub const PROP_CNT: Input = Input(32);
}
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Key(u32);
impl Key {
    pub const fn new(value: u32) -> Key {
        Key(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Key {
    fn from(value: u32) -> Key {
        Key(value)
    }
}
impl From<Key> for u32 {
    fn from(value: Key) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Key {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Key {
    #[doc(alias = "KEY_RESERVED")]
    pub const RESERVED: Key = Key(0);
    #[doc(alias = "KEY_ESC")]
    pub const ESC: Key = Key(1);
    #[doc(alias = "KEY_1")]
    pub const _1: Key = Key(2);
    #[doc(alias = "KEY_2")]
    pub const _2: Key = Key(3);
    #[doc(alias = "KEY_3")]
    pub const _3: Key = Key(4);
    #[doc(alias = "KEY_4")]
    pub const _4: Key = Key(5);
    #[doc(alias = "KEY_5")]
    pub const _5: Key = Key(6);
    #[doc(alias = "KEY_6")]
    pub const _6: Key = Key(7);
    #[doc(alias = "KEY_7")]
    pub const _7: Key = Key(8);
    #[doc(alias = "KEY_8")]
    pub const _8: Key = Key(9);
    #[doc(alias = "KEY_9")]
    pub const _9: Key = Key(10);
    #[doc(alias = "KEY_0")]
    pub const _0: Key = Key(11);
    #[doc(alias = "KEY_MINUS")]
    pub const MINUS: Key = Key(12);
    #[doc(alias = "KEY_EQUAL")]
    pub const EQUAL: Key = Key(13);
    #[doc(alias = "KEY_BACKSPACE")]
    pub const BACKSPACE: Key = Key(14);
    #[doc(alias = "KEY_TAB")]
    pub const TAB: Key = Key(15);
    #[doc(alias = "KEY_Q")]
    pub const Q: Key = Key(16);
    #[doc(alias = "KEY_W")]
    pub const W: Key = Key(17);
    #[doc(alias = "KEY_E")]
    pub const E: Key = Key(18);
    #[doc(alias = "KEY_R")]
    pub const R: Key = Key(19);
    #[doc(alias = "KEY_T")]
    pub const T: Key = Key(20);
    #[doc(alias = "KEY_Y")]
    pub const Y: Key = Key(21);
    #[doc(alias = "KEY_U")]
    pub const U: Key = Key(22);
    #[doc(alias = "KEY_I")]
    pub const I: Key = Key(23);
    #[doc(alias = "KEY_O")]
    pub const O: Key = Key(24);
    #[doc(alias = "KEY_P")]
    pub const P: Key = Key(25);
    #[doc(alias = "KEY_LEFTBRACE")]
    pub const LEFTBRACE: Key = Key(26);
    #[doc(alias = "KEY_RIGHTBRACE")]
    pub const RIGHTBRACE: Key = Key(27);
    #[doc(alias = "KEY_ENTER")]
    pub const ENTER: Key = Key(28);
    #[doc(alias = "KEY_LEFTCTRL")]
    pub const LEFTCTRL: Key = Key(29);
    #[doc(alias = "KEY_A")]
    pub const A: Key = Key(30);
    #[doc(alias = "KEY_S")]
    pub const S: Key = Key(31);
    #[doc(alias = "KEY_D")]
    pub const D: Key = Key(32);
    #[doc(alias = "KEY_F")]
    pub const F: Key = Key(33);
    #[doc(alias = "KEY_G")]
    pub const G: Key = Key(34);
    #[doc(alias = "KEY_H")]
    pub const H: Key = Key(35);
    #[doc(alias = "KEY_J")]
    pub const J: Key = Key(36);
    #[doc(alias = "KEY_K")]
    pub const K: Key = Key(37);
    #[doc(alias = "KEY_L")]
    pub const L: Key = Key(38);
    #[doc(alias = "KEY_SEMICOLON")]
    pub const SEMICOLON: Key = Key(39);
    #[doc(alias = "KEY_APOSTROPHE")]
    pub const APOSTROPHE: Key = Key(40);
    #[doc(alias = "KEY_GRAVE")]
    pub const GRAVE: Key = Key(41);
    #[doc(alias = "KEY_LEFTSHIFT")]
    pub const LEFTSHIFT: Key = Key(42);
    #[doc(alias = "KEY_BACKSLASH")]
    pub const BACKSLASH: Key = Key(43);
    #[doc(alias = "KEY_Z")]
    pub const Z: Key = Key(44);
    #[doc(alias = "KEY_X")]
    pub const X: Key = Key(45);
    #[doc(alias = "KEY_C")]
    pub const C: Key = Key(46);
    #[doc(alias = "KEY_V")]
    pub const V: Key = Key(47);
    #[doc(alias = "KEY_B")]
    pub const B: Key = Key(48);
    #[doc(alias = "KEY_N")]
    pub const N: Key = Key(49);
    #[doc(alias = "KEY_M")]
    pub const M: Key = Key(50);
    #[doc(alias = "KEY_COMMA")]
    pub const COMMA: Key = Key(51);
    #[doc(alias = "KEY_DOT")]
    pub const DOT: Key = Key(52);
    #[doc(alias = "KEY_SLASH")]
    pub const SLASH: Key = Key(53);
    #[doc(alias = "KEY_RIGHTSHIFT")]
    pub const RIGHTSHIFT: Key = Key(54);
    #[doc(alias = "KEY_KPASTERISK")]
    pub const KPASTERISK: Key = Key(55);
    #[doc(alias = "KEY_LEFTALT")]
    pub const LEFTALT: Key = Key(56);
    #[doc(alias = "KEY_SPACE")]
    pub const SPACE: Key = Key(57);
    #[doc(alias = "KEY_CAPSLOCK")]
    pub const CAPSLOCK: Key = Key(58);
    #[doc(alias = "KEY_F1")]
    pub const F1: Key = Key(59);
    #[doc(alias = "KEY_F2")]
    pub const F2: Key = Key(60);
    #[doc(alias = "KEY_F3")]
    pub const F3: Key = Key(61);
    #[doc(alias = "KEY_F4")]
    pub const F4: Key = Key(62);
    #[doc(alias = "KEY_F5")]
    pub const F5: Key = Key(63);
    #[doc(alias = "KEY_F6")]
    pub const F6: Key = Key(64);
    #[doc(alias = "KEY_F7")]
    pub const F7: Key = Key(65);
    #[doc(alias = "KEY_F8")]
    pub const F8: Key = Key(66);
    #[doc(alias = "KEY_F9")]
    pub const F9: Key = Key(67);
    #[doc(alias = "KEY_F10")]
    pub const F10: Key = Key(68);
    #[doc(alias = "KEY_NUMLOCK")]
    pub const NUMLOCK: Key = Key(69);
    #[doc(alias = "KEY_SCROLLLOCK")]
    pub const SCROLLLOCK: Key = Key(70);
    #[doc(alias = "KEY_KP7")]
    pub const KP7: Key = Key(71);
    #[doc(alias = "KEY_KP8")]
    pub const KP8: Key = Key(72);
    #[doc(alias = "KEY_KP9")]
    pub const KP9: Key = Key(73);
    #[doc(alias = "KEY_KPMINUS")]
    pub const KPMINUS: Key = Key(74);
    #[doc(alias = "KEY_KP4")]
    pub const KP4: Key = Key(75);
    #[doc(alias = "KEY_KP5")]
    pub const KP5: Key = Key(76);
    #[doc(alias = "KEY_KP6")]
    pub const KP6: Key = Key(77);
    #[doc(alias = "KEY_KPPLUS")]
    pub const KPPLUS: Key = Key(78);
    #[doc(alias = "KEY_KP1")]
    pub const KP1: Key = Key(79);
    #[doc(alias = "KEY_KP2")]
    pub const KP2: Key = Key(80);
    #[doc(alias = "KEY_KP3")]
    pub const KP3: Key = Key(81);
    #[doc(alias = "KEY_KP0")]
    pub const KP0: Key = Key(82);
    #[doc(alias = "KEY_KPDOT")]
    pub const KPDOT: Key = Key(83);
    #[doc(alias = "KEY_ZENKAKUHANKAKU")]
    pub const ZENKAKUHANKAKU: Key = Key(85);
    #[doc(alias = "KEY_102ND")]
    pub const _102ND: Key = Key(86);
    #[doc(alias = "KEY_F11")]
    pub const F11: Key = Key(87);
    #[doc(alias = "KEY_F12")]
    pub const F12: Key = Key(88);
    #[doc(alias = "KEY_RO")]
    pub const RO: Key = Key(89);
    #[doc(alias = "KEY_KATAKANA")]
    pub const KATAKANA: Key = Key(90);
    #[doc(alias = "KEY_HIRAGANA")]
    pub const HIRAGANA: Key = Key(91);
    #[doc(alias = "KEY_HENKAN")]
    pub const HENKAN: Key = Key(92);
    #[doc(alias = "KEY_KATAKANAHIRAGANA")]
    pub const KATAKANAHIRAGANA: Key = Key(93);
    #[doc(alias = "KEY_MUHENKAN")]
    pub const MUHENKAN: Key = Key(94);
    #[doc(alias = "KEY_KPJPCOMMA")]
    pub const KPJPCOMMA: Key = Key(95);
    #[doc(alias = "KEY_KPENTER")]
    pub const KPENTER: Key = Key(96);
    #[doc(alias = "KEY_RIGHTCTRL")]
    pub const RIGHTCTRL: Key = Key(97);
    #[doc(alias = "KEY_KPSLASH")]
    pub const KPSLASH: Key = Key(98);
    #[doc(alias = "KEY_SYSRQ")]
    pub const SYSRQ: Key = Key(99);
    #[doc(alias = "KEY_RIGHTALT")]
    pub const RIGHTALT: Key = Key(100);
    #[doc(alias = "KEY_LINEFEED")]
    pub const LINEFEED: Key = Key(101);
    #[doc(alias = "KEY_HOME")]
    pub const HOME: Key = Key(102);
    #[doc(alias = "KEY_UP")]
    pub const UP: Key = Key(103);
    #[doc(alias = "KEY_PAGEUP")]
    pub const PAGEUP: Key = Key(104);
    #[doc(alias = "KEY_LEFT")]
    pub const LEFT: Key = Key(105);
    #[doc(alias = "KEY_RIGHT")]
    pub const RIGHT: Key = Key(106);
    #[doc(alias = "KEY_END")]
    pub const END: Key = Key(107);
    #[doc(alias = "KEY_DOWN")]
    pub const DOWN: Key = Key(108);
    #[doc(alias = "KEY_PAGEDOWN")]
    pub const PAGEDOWN: Key = Key(109);
    #[doc(alias = "KEY_INSERT")]
    pub const INSERT: Key = Key(110);
    #[doc(alias = "KEY_DELETE")]
    pub const DELETE: Key = Key(111);
    #[doc(alias = "KEY_MACRO")]
    pub const MACRO: Key = Key(112);
    #[doc(alias = "KEY_MUTE")]
    pub const MUTE: Key = Key(113);
    #[doc(alias = "KEY_VOLUMEDOWN")]
    pub const VOLUMEDOWN: Key = Key(114);
    #[doc(alias = "KEY_VOLUMEUP")]
    pub const VOLUMEUP: Key = Key(115);
    #[doc(alias = "KEY_POWER")]
    pub const POWER: Key = Key(116);
    #[doc(alias = "KEY_KPEQUAL")]
    pub const KPEQUAL: Key = Key(117);
    #[doc(alias = "KEY_KPPLUSMINUS")]
    pub const KPPLUSMINUS: Key = Key(118);
    #[doc(alias = "KEY_PAUSE")]
    pub const PAUSE: Key = Key(119);
    #[doc(alias = "KEY_SCALE")]
    pub const SCALE: Key = Key(120);
    #[doc(alias = "KEY_KPCOMMA")]
    pub const KPCOMMA: Key = Key(121);
    #[doc(alias = "KEY_HANGEUL")]
    pub const HANGEUL: Key = Key(122);
    #[doc(alias = "KEY_HANGUEL")]
    pub const HANGUEL: Key = Key(122);
    #[doc(alias = "KEY_HANJA")]
    pub const HANJA: Key = Key(123);
    #[doc(alias = "KEY_YEN")]
    pub const YEN: Key = Key(124);
    #[doc(alias = "KEY_LEFTMETA")]
    pub const LEFTMETA: Key = Key(125);
    #[doc(alias = "KEY_RIGHTMETA")]
    pub const RIGHTMETA: Key = Key(126);
    #[doc(alias = "KEY_COMPOSE")]
    pub const COMPOSE: Key = Key(127);
    #[doc(alias = "KEY_STOP")]
    pub const STOP: Key = Key(128);
    #[doc(alias = "KEY_AGAIN")]
    pub const AGAIN: Key = Key(129);
    #[doc(alias = "KEY_PROPS")]
    pub const PROPS: Key = Key(130);
    #[doc(alias = "KEY_UNDO")]
    pub const UNDO: Key = Key(131);
    #[doc(alias = "KEY_FRONT")]
    pub const FRONT: Key = Key(132);
    #[doc(alias = "KEY_COPY")]
    pub const COPY: Key = Key(133);
    #[doc(alias = "KEY_OPEN")]
    pub const OPEN: Key = Key(134);
    #[doc(alias = "KEY_PASTE")]
    pub const PASTE: Key = Key(135);
    #[doc(alias = "KEY_FIND")]
    pub const FIND: Key = Key(136);
    #[doc(alias = "KEY_CUT")]
    pub const CUT: Key = Key(137);
    #[doc(alias = "KEY_HELP")]
    pub const HELP: Key = Key(138);
    #[doc(alias = "KEY_MENU")]
    pub const MENU: Key = Key(139);
    #[doc(alias = "KEY_CALC")]
    pub const CALC: Key = Key(140);
    #[doc(alias = "KEY_SETUP")]
    pub const SETUP: Key = Key(141);
    #[doc(alias = "KEY_SLEEP")]
    pub const SLEEP: Key = Key(142);
    #[doc(alias = "KEY_WAKEUP")]
    pub const WAKEUP: Key = Key(143);
    #[doc(alias = "KEY_FILE")]
    pub const FILE: Key = Key(144);
    #[doc(alias = "KEY_SENDFILE")]
    pub const SENDFILE: Key = Key(145);
    #[doc(alias = "KEY_DELETEFILE")]
    pub const DELETEFILE: Key = Key(146);
    #[doc(alias = "KEY_XFER")]
    pub const XFER: Key = Key(147);
    #[doc(alias = "KEY_PROG1")]
    pub const PROG1: Key = Key(148);
    #[doc(alias = "KEY_PROG2")]
    pub const PROG2: Key = Key(149);
    #[doc(alias = "KEY_WWW")]
    pub const WWW: Key = Key(150);
    #[doc(alias = "KEY_MSDOS")]
    pub const MSDOS: Key = Key(151);
    #[doc(alias = "KEY_COFFEE")]
    pub const COFFEE: Key = Key(152);
    #[doc(alias = "KEY_SCREENLOCK")]
    pub const SCREENLOCK: Key = Key(152);
    #[doc(alias = "KEY_ROTATE_DISPLAY")]
    pub const ROTATE_DISPLAY: Key = Key(153);
    #[doc(alias = "KEY_DIRECTION")]
    pub const DIRECTION: Key = Key(153);
    #[doc(alias = "KEY_CYCLEWINDOWS")]
    pub const CYCLEWINDOWS: Key = Key(154);
    #[doc(alias = "KEY_MAIL")]
    pub const MAIL: Key = Key(155);
    #[doc(alias = "KEY_BOOKMARKS")]
    pub const BOOKMARKS: Key = Key(156);
    #[doc(alias = "KEY_COMPUTER")]
    pub const COMPUTER: Key = Key(157);
    #[doc(alias = "KEY_BACK")]
    pub const BACK: Key = Key(158);
    #[doc(alias = "KEY_FORWARD")]
    pub const FORWARD: Key = Key(159);
    #[doc(alias = "KEY_CLOSECD")]
    pub const CLOSECD: Key = Key(160);
    #[doc(alias = "KEY_EJECTCD")]
    pub const EJECTCD: Key = Key(161);
    #[doc(alias = "KEY_EJECTCLOSECD")]
    pub const EJECTCLOSECD: Key = Key(162);
    #[doc(alias = "KEY_NEXTSONG")]
    pub const NEXTSONG: Key = Key(163);
    #[doc(alias = "KEY_PLAYPAUSE")]
    pub const PLAYPAUSE: Key = Key(164);
    #[doc(alias = "KEY_PREVIOUSSONG")]
    pub const PREVIOUSSONG: Key = Key(165);
    #[doc(alias = "KEY_STOPCD")]
    pub const STOPCD: Key = Key(166);
    #[doc(alias = "KEY_RECORD")]
    pub const RECORD: Key = Key(167);
    #[doc(alias = "KEY_REWIND")]
    pub const REWIND: Key = Key(168);
    #[doc(alias = "KEY_PHONE")]
    pub const PHONE: Key = Key(169);
    #[doc(alias = "KEY_ISO")]
    pub const ISO: Key = Key(170);
    #[doc(alias = "KEY_CONFIG")]
    pub const CONFIG: Key = Key(171);
    #[doc(alias = "KEY_HOMEPAGE")]
    pub const HOMEPAGE: Key = Key(172);
    #[doc(alias = "KEY_REFRESH")]
    pub const REFRESH: Key = Key(173);
    #[doc(alias = "KEY_EXIT")]
    pub const EXIT: Key = Key(174);
    #[doc(alias = "KEY_MOVE")]
    pub const MOVE: Key = Key(175);
    #[doc(alias = "KEY_EDIT")]
    pub const EDIT: Key = Key(176);
    #[doc(alias = "KEY_SCROLLUP")]
    pub const SCROLLUP: Key = Key(177);
    #[doc(alias = "KEY_SCROLLDOWN")]
    pub const SCROLLDOWN: Key = Key(178);
    #[doc(alias = "KEY_KPLEFTPAREN")]
    pub const KPLEFTPAREN: Key = Key(179);
    #[doc(alias = "KEY_KPRIGHTPAREN")]
    pub const KPRIGHTPAREN: Key = Key(180);
    #[doc(alias = "KEY_NEW")]
    pub const NEW: Key = Key(181);
    #[doc(alias = "KEY_REDO")]
    pub const REDO: Key = Key(182);
    #[doc(alias = "KEY_F13")]
    pub const F13: Key = Key(183);
    #[doc(alias = "KEY_F14")]
    pub const F14: Key = Key(184);
    #[doc(alias = "KEY_F15")]
    pub const F15: Key = Key(185);
    #[doc(alias = "KEY_F16")]
    pub const F16: Key = Key(186);
    #[doc(alias = "KEY_F17")]
    pub const F17: Key = Key(187);
    #[doc(alias = "KEY_F18")]
    pub const F18: Key = Key(188);
    #[doc(alias = "KEY_F19")]
    pub const F19: Key = Key(189);
    #[doc(alias = "KEY_F20")]
    pub const F20: Key = Key(190);
    #[doc(alias = "KEY_F21")]
    pub const F21: Key = Key(191);
    #[doc(alias = "KEY_F22")]
    pub const F22: Key = Key(192);
    #[doc(alias = "KEY_F23")]
    pub const F23: Key = Key(193);
    #[doc(alias = "KEY_F24")]
    pub const F24: Key = Key(194);
    #[doc(alias = "KEY_PLAYCD")]
    pub const PLAYCD: Key = Key(200);
    #[doc(alias = "KEY_PAUSECD")]
    pub const PAUSECD: Key = Key(201);
    #[doc(alias = "KEY_PROG3")]
    pub const PROG3: Key = Key(202);
    #[doc(alias = "KEY_PROG4")]
    pub const PROG4: Key = Key(203);
    #[doc(alias = "KEY_DASHBOARD")]
    pub const DASHBOARD: Key = Key(204);
    #[doc(alias = "KEY_SUSPEND")]
    pub const SUSPEND: Key = Key(205);
    #[doc(alias = "KEY_CLOSE")]
    pub const CLOSE: Key = Key(206);
    #[doc(alias = "KEY_PLAY")]
    pub const PLAY: Key = Key(207);
    #[doc(alias = "KEY_FASTFORWARD")]
    pub const FASTFORWARD: Key = Key(208);
    #[doc(alias = "KEY_BASSBOOST")]
    pub const BASSBOOST: Key = Key(209);
    #[doc(alias = "KEY_PRINT")]
    pub const PRINT: Key = Key(210);
    #[doc(alias = "KEY_HP")]
    pub const HP: Key = Key(211);
    #[doc(alias = "KEY_CAMERA")]
    pub const CAMERA: Key = Key(212);
    #[doc(alias = "KEY_SOUND")]
    pub const SOUND: Key = Key(213);
    #[doc(alias = "KEY_QUESTION")]
    pub const QUESTION: Key = Key(214);
    #[doc(alias = "KEY_EMAIL")]
    pub const EMAIL: Key = Key(215);
    #[doc(alias = "KEY_CHAT")]
    pub const CHAT: Key = Key(216);
    #[doc(alias = "KEY_SEARCH")]
    pub const SEARCH: Key = Key(217);
    #[doc(alias = "KEY_CONNECT")]
    pub const CONNECT: Key = Key(218);
    #[doc(alias = "KEY_FINANCE")]
    pub const FINANCE: Key = Key(219);
    #[doc(alias = "KEY_SPORT")]
    pub const SPORT: Key = Key(220);
    #[doc(alias = "KEY_SHOP")]
    pub const SHOP: Key = Key(221);
    #[doc(alias = "KEY_ALTERASE")]
    pub const ALTERASE: Key = Key(222);
    #[doc(alias = "KEY_CANCEL")]
    pub const CANCEL: Key = Key(223);
    #[doc(alias = "KEY_BRIGHTNESSDOWN")]
    pub const BRIGHTNESSDOWN: Key = Key(224);
    #[doc(alias = "KEY_BRIGHTNESSUP")]
    pub const BRIGHTNESSUP: Key = Key(225);
    #[doc(alias = "KEY_MEDIA")]
    pub const MEDIA: Key = Key(226);
    #[doc(alias = "KEY_SWITCHVIDEOMODE")]
    pub const SWITCHVIDEOMODE: Key = Key(227);
    #[doc(alias = "KEY_KBDILLUMTOGGLE")]
    pub const KBDILLUMTOGGLE: Key = Key(228);
    #[doc(alias = "KEY_KBDILLUMDOWN")]
    pub const KBDILLUMDOWN: Key = Key(229);
    #[doc(alias = "KEY_KBDILLUMUP")]
    pub const KBDILLUMUP: Key = Key(230);
    #[doc(alias = "KEY_SEND")]
    pub const SEND: Key = Key(231);
    #[doc(alias = "KEY_REPLY")]
    pub const REPLY: Key = Key(232);
    #[doc(alias = "KEY_FORWARDMAIL")]
    pub const FORWARDMAIL: Key = Key(233);
    #[doc(alias = "KEY_SAVE")]
    pub const SAVE: Key = Key(234);
    #[doc(alias = "KEY_DOCUMENTS")]
    pub const DOCUMENTS: Key = Key(235);
    #[doc(alias = "KEY_BATTERY")]
    pub const BATTERY: Key = Key(236);
    #[doc(alias = "KEY_BLUETOOTH")]
    pub const BLUETOOTH: Key = Key(237);
    #[doc(alias = "KEY_WLAN")]
    pub const WLAN: Key = Key(238);
    #[doc(alias = "KEY_UWB")]
    pub const UWB: Key = Key(239);
    #[doc(alias = "KEY_UNKNOWN")]
    pub const UNKNOWN: Key = Key(240);
    #[doc(alias = "KEY_VIDEO_NEXT")]
    pub const VIDEO_NEXT: Key = Key(241);
    #[doc(alias = "KEY_VIDEO_PREV")]
    pub const VIDEO_PREV: Key = Key(242);
    #[doc(alias = "KEY_BRIGHTNESS_CYCLE")]
    pub const BRIGHTNESS_CYCLE: Key = Key(243);
    #[doc(alias = "KEY_BRIGHTNESS_AUTO")]
    pub const BRIGHTNESS_AUTO: Key = Key(244);
    #[doc(alias = "KEY_BRIGHTNESS_ZERO")]
    pub const BRIGHTNESS_ZERO: Key = Key(244);
    #[doc(alias = "KEY_DISPLAY_OFF")]
    pub const DISPLAY_OFF: Key = Key(245);
    #[doc(alias = "KEY_WWAN")]
    pub const WWAN: Key = Key(246);
    #[doc(alias = "KEY_WIMAX")]
    pub const WIMAX: Key = Key(246);
    #[doc(alias = "KEY_RFKILL")]
    pub const RFKILL: Key = Key(247);
    #[doc(alias = "KEY_MICMUTE")]
    pub const MICMUTE: Key = Key(248);
    #[doc(alias = "KEY_OK")]
    pub const OK: Key = Key(352);
    #[doc(alias = "KEY_SELECT")]
    pub const SELECT: Key = Key(353);
    #[doc(alias = "KEY_GOTO")]
    pub const GOTO: Key = Key(354);
    #[doc(alias = "KEY_CLEAR")]
    pub const CLEAR: Key = Key(355);
    #[doc(alias = "KEY_POWER2")]
    pub const POWER2: Key = Key(356);
    #[doc(alias = "KEY_OPTION")]
    pub const OPTION: Key = Key(357);
    #[doc(alias = "KEY_INFO")]
    pub const INFO: Key = Key(358);
    #[doc(alias = "KEY_TIME")]
    pub const TIME: Key = Key(359);
    #[doc(alias = "KEY_VENDOR")]
    pub const VENDOR: Key = Key(360);
    #[doc(alias = "KEY_ARCHIVE")]
    pub const ARCHIVE: Key = Key(361);
    #[doc(alias = "KEY_PROGRAM")]
    pub const PROGRAM: Key = Key(362);
    #[doc(alias = "KEY_CHANNEL")]
    pub const CHANNEL: Key = Key(363);
    #[doc(alias = "KEY_FAVORITES")]
    pub const FAVORITES: Key = Key(364);
    #[doc(alias = "KEY_EPG")]
    pub const EPG: Key = Key(365);
    #[doc(alias = "KEY_PVR")]
    pub const PVR: Key = Key(366);
    #[doc(alias = "KEY_MHP")]
    pub const MHP: Key = Key(367);
    #[doc(alias = "KEY_LANGUAGE")]
    pub const LANGUAGE: Key = Key(368);
    #[doc(alias = "KEY_TITLE")]
    pub const TITLE: Key = Key(369);
    #[doc(alias = "KEY_SUBTITLE")]
    pub const SUBTITLE: Key = Key(370);
    #[doc(alias = "KEY_ANGLE")]
    pub const ANGLE: Key = Key(371);
    #[doc(alias = "KEY_FULL_SCREEN")]
    pub const FULL_SCREEN: Key = Key(372);
    #[doc(alias = "KEY_ZOOM")]
    pub const ZOOM: Key = Key(372);
    #[doc(alias = "KEY_MODE")]
    pub const MODE: Key = Key(373);
    #[doc(alias = "KEY_KEYBOARD")]
    pub const KEYBOARD: Key = Key(374);
    #[doc(alias = "KEY_ASPECT_RATIO")]
    pub const ASPECT_RATIO: Key = Key(375);
    #[doc(alias = "KEY_SCREEN")]
    pub const SCREEN: Key = Key(375);
    #[doc(alias = "KEY_PC")]
    pub const PC: Key = Key(376);
    #[doc(alias = "KEY_TV")]
    pub const TV: Key = Key(377);
    #[doc(alias = "KEY_TV2")]
    pub const TV2: Key = Key(378);
    #[doc(alias = "KEY_VCR")]
    pub const VCR: Key = Key(379);
    #[doc(alias = "KEY_VCR2")]
    pub const VCR2: Key = Key(380);
    #[doc(alias = "KEY_SAT")]
    pub const SAT: Key = Key(381);
    #[doc(alias = "KEY_SAT2")]
    pub const SAT2: Key = Key(382);
    #[doc(alias = "KEY_CD")]
    pub const CD: Key = Key(383);
    #[doc(alias = "KEY_TAPE")]
    pub const TAPE: Key = Key(384);
    #[doc(alias = "KEY_RADIO")]
    pub const RADIO: Key = Key(385);
    #[doc(alias = "KEY_TUNER")]
    pub const TUNER: Key = Key(386);
    #[doc(alias = "KEY_PLAYER")]
    pub const PLAYER: Key = Key(387);
    #[doc(alias = "KEY_TEXT")]
    pub const TEXT: Key = Key(388);
    #[doc(alias = "KEY_DVD")]
    pub const DVD: Key = Key(389);
    #[doc(alias = "KEY_AUX")]
    pub const AUX: Key = Key(390);
    #[doc(alias = "KEY_MP3")]
    pub const MP3: Key = Key(391);
    #[doc(alias = "KEY_AUDIO")]
    pub const AUDIO: Key = Key(392);
    #[doc(alias = "KEY_VIDEO")]
    pub const VIDEO: Key = Key(393);
    #[doc(alias = "KEY_DIRECTORY")]
    pub const DIRECTORY: Key = Key(394);
    #[doc(alias = "KEY_LIST")]
    pub const LIST: Key = Key(395);
    #[doc(alias = "KEY_MEMO")]
    pub const MEMO: Key = Key(396);
    #[doc(alias = "KEY_CALENDAR")]
    pub const CALENDAR: Key = Key(397);
    #[doc(alias = "KEY_RED")]
    pub const RED: Key = Key(398);
    #[doc(alias = "KEY_GREEN")]
    pub const GREEN: Key = Key(399);
    #[doc(alias = "KEY_YELLOW")]
    pub const YELLOW: Key = Key(400);
    #[doc(alias = "KEY_BLUE")]
    pub const BLUE: Key = Key(401);
    #[doc(alias = "KEY_CHANNELUP")]
    pub const CHANNELUP: Key = Key(402);
    #[doc(alias = "KEY_CHANNELDOWN")]
    pub const CHANNELDOWN: Key = Key(403);
    #[doc(alias = "KEY_FIRST")]
    pub const FIRST: Key = Key(404);
    #[doc(alias = "KEY_LAST")]
    pub const LAST: Key = Key(405);
    #[doc(alias = "KEY_AB")]
    pub const AB: Key = Key(406);
    #[doc(alias = "KEY_NEXT")]
    pub const NEXT: Key = Key(407);
    #[doc(alias = "KEY_RESTART")]
    pub const RESTART: Key = Key(408);
    #[doc(alias = "KEY_SLOW")]
    pub const SLOW: Key = Key(409);
    #[doc(alias = "KEY_SHUFFLE")]
    pub const SHUFFLE: Key = Key(410);
    #[doc(alias = "KEY_BREAK")]
    pub const BREAK: Key = Key(411);
    #[doc(alias = "KEY_PREVIOUS")]
    pub const PREVIOUS: Key = Key(412);
    #[doc(alias = "KEY_DIGITS")]
    pub const DIGITS: Key = Key(413);
    #[doc(alias = "KEY_TEEN")]
    pub const TEEN: Key = Key(414);
    #[doc(alias = "KEY_TWEN")]
    pub const TWEN: Key = Key(415);
    #[doc(alias = "KEY_VIDEOPHONE")]
    pub const VIDEOPHONE: Key = Key(416);
    #[doc(alias = "KEY_GAMES")]
    pub const GAMES: Key = Key(417);
    #[doc(alias = "KEY_ZOOMIN")]
    pub const ZOOMIN: Key = Key(418);
    #[doc(alias = "KEY_ZOOMOUT")]
    pub const ZOOMOUT: Key = Key(419);
    #[doc(alias = "KEY_ZOOMRESET")]
    pub const ZOOMRESET: Key = Key(420);
    #[doc(alias = "KEY_WORDPROCESSOR")]
    pub const WORDPROCESSOR: Key = Key(421);
    #[doc(alias = "KEY_EDITOR")]
    pub const EDITOR: Key = Key(422);
    #[doc(alias = "KEY_SPREADSHEET")]
    pub const SPREADSHEET: Key = Key(423);
    #[doc(alias = "KEY_GRAPHICSEDITOR")]
    pub const GRAPHICSEDITOR: Key = Key(424);
    #[doc(alias = "KEY_PRESENTATION")]
    pub const PRESENTATION: Key = Key(425);
    #[doc(alias = "KEY_DATABASE")]
    pub const DATABASE: Key = Key(426);
    #[doc(alias = "KEY_NEWS")]
    pub const NEWS: Key = Key(427);
    #[doc(alias = "KEY_VOICEMAIL")]
    pub const VOICEMAIL: Key = Key(428);
    #[doc(alias = "KEY_ADDRESSBOOK")]
    pub const ADDRESSBOOK: Key = Key(429);
    #[doc(alias = "KEY_MESSENGER")]
    pub const MESSENGER: Key = Key(430);
    #[doc(alias = "KEY_DISPLAYTOGGLE")]
    pub const DISPLAYTOGGLE: Key = Key(431);
    #[doc(alias = "KEY_BRIGHTNESS_TOGGLE")]
    pub const BRIGHTNESS_TOGGLE: Key = Key(431);
    #[doc(alias = "KEY_SPELLCHECK")]
    pub const SPELLCHECK: Key = Key(432);
    #[doc(alias = "KEY_LOGOFF")]
    pub const LOGOFF: Key = Key(433);
    #[doc(alias = "KEY_DOLLAR")]
    pub const DOLLAR: Key = Key(434);
    #[doc(alias = "KEY_EURO")]
    pub const EURO: Key = Key(435);
    #[doc(alias = "KEY_FRAMEBACK")]
    pub const FRAMEBACK: Key = Key(436);
    #[doc(alias = "KEY_FRAMEFORWARD")]
    pub const FRAMEFORWARD: Key = Key(437);
    #[doc(alias = "KEY_CONTEXT_MENU")]
    pub const CONTEXT_MENU: Key = Key(438);
    #[doc(alias = "KEY_MEDIA_REPEAT")]
    pub const MEDIA_REPEAT: Key = Key(439);
    #[doc(alias = "KEY_10CHANNELSUP")]
    pub const _10CHANNELSUP: Key = Key(440);
    #[doc(alias = "KEY_10CHANNELSDOWN")]
    pub const _10CHANNELSDOWN: Key = Key(441);
    #[doc(alias = "KEY_IMAGES")]
    pub const IMAGES: Key = Key(442);
    #[doc(alias = "KEY_NOTIFICATION_CENTER")]
    pub const NOTIFICATION_CENTER: Key = Key(444);
    #[doc(alias = "KEY_PICKUP_PHONE")]
    pub const PICKUP_PHONE: Key = Key(445);
    #[doc(alias = "KEY_HANGUP_PHONE")]
    pub const HANGUP_PHONE: Key = Key(446);
    #[doc(alias = "KEY_DEL_EOL")]
    pub const DEL_EOL: Key = Key(448);
    #[doc(alias = "KEY_DEL_EOS")]
    pub const DEL_EOS: Key = Key(449);
    #[doc(alias = "KEY_INS_LINE")]
    pub const INS_LINE: Key = Key(450);
    #[doc(alias = "KEY_DEL_LINE")]
    pub const DEL_LINE: Key = Key(451);
    #[doc(alias = "KEY_FN")]
    pub const FN: Key = Key(464);
    #[doc(alias = "KEY_FN_ESC")]
    pub const FN_ESC: Key = Key(465);
    #[doc(alias = "KEY_FN_F1")]
    pub const FN_F1: Key = Key(466);
    #[doc(alias = "KEY_FN_F2")]
    pub const FN_F2: Key = Key(467);
    #[doc(alias = "KEY_FN_F3")]
    pub const FN_F3: Key = Key(468);
    #[doc(alias = "KEY_FN_F4")]
    pub const FN_F4: Key = Key(469);
    #[doc(alias = "KEY_FN_F5")]
    pub const FN_F5: Key = Key(470);
    #[doc(alias = "KEY_FN_F6")]
    pub const FN_F6: Key = Key(471);
    #[doc(alias = "KEY_FN_F7")]
    pub const FN_F7: Key = Key(472);
    #[doc(alias = "KEY_FN_F8")]
    pub const FN_F8: Key = Key(473);
    #[doc(alias = "KEY_FN_F9")]
    pub const FN_F9: Key = Key(474);
    #[doc(alias = "KEY_FN_F10")]
    pub const FN_F10: Key = Key(475);
    #[doc(alias = "KEY_FN_F11")]
    pub const FN_F11: Key = Key(476);
    #[doc(alias = "KEY_FN_F12")]
    pub const FN_F12: Key = Key(477);
    #[doc(alias = "KEY_FN_1")]
    pub const FN_1: Key = Key(478);
    #[doc(alias = "KEY_FN_2")]
    pub const FN_2: Key = Key(479);
    #[doc(alias = "KEY_FN_D")]
    pub const FN_D: Key = Key(480);
    #[doc(alias = "KEY_FN_E")]
    pub const FN_E: Key = Key(481);
    #[doc(alias = "KEY_FN_F")]
    pub const FN_F: Key = Key(482);
    #[doc(alias = "KEY_FN_S")]
    pub const FN_S: Key = Key(483);
    #[doc(alias = "KEY_FN_B")]
    pub const FN_B: Key = Key(484);
    #[doc(alias = "KEY_FN_RIGHT_SHIFT")]
    pub const FN_RIGHT_SHIFT: Key = Key(485);
    #[doc(alias = "KEY_BRL_DOT1")]
    pub const BRL_DOT1: Key = Key(497);
    #[doc(alias = "KEY_BRL_DOT2")]
    pub const BRL_DOT2: Key = Key(498);
    #[doc(alias = "KEY_BRL_DOT3")]
    pub const BRL_DOT3: Key = Key(499);
    #[doc(alias = "KEY_BRL_DOT4")]
    pub const BRL_DOT4: Key = Key(500);
    #[doc(alias = "KEY_BRL_DOT5")]
    pub const BRL_DOT5: Key = Key(501);
    #[doc(alias = "KEY_BRL_DOT6")]
    pub const BRL_DOT6: Key = Key(502);
    #[doc(alias = "KEY_BRL_DOT7")]
    pub const BRL_DOT7: Key = Key(503);
    #[doc(alias = "KEY_BRL_DOT8")]
    pub const BRL_DOT8: Key = Key(504);
    #[doc(alias = "KEY_BRL_DOT9")]
    pub const BRL_DOT9: Key = Key(505);
    #[doc(alias = "KEY_BRL_DOT10")]
    pub const BRL_DOT10: Key = Key(506);
    #[doc(alias = "KEY_NUMERIC_0")]
    pub const NUMERIC_0: Key = Key(512);
    #[doc(alias = "KEY_NUMERIC_1")]
    pub const NUMERIC_1: Key = Key(513);
    #[doc(alias = "KEY_NUMERIC_2")]
    pub const NUMERIC_2: Key = Key(514);
    #[doc(alias = "KEY_NUMERIC_3")]
    pub const NUMERIC_3: Key = Key(515);
    #[doc(alias = "KEY_NUMERIC_4")]
    pub const NUMERIC_4: Key = Key(516);
    #[doc(alias = "KEY_NUMERIC_5")]
    pub const NUMERIC_5: Key = Key(517);
    #[doc(alias = "KEY_NUMERIC_6")]
    pub const NUMERIC_6: Key = Key(518);
    #[doc(alias = "KEY_NUMERIC_7")]
    pub const NUMERIC_7: Key = Key(519);
    #[doc(alias = "KEY_NUMERIC_8")]
    pub const NUMERIC_8: Key = Key(520);
    #[doc(alias = "KEY_NUMERIC_9")]
    pub const NUMERIC_9: Key = Key(521);
    #[doc(alias = "KEY_NUMERIC_STAR")]
    pub const NUMERIC_STAR: Key = Key(522);
    #[doc(alias = "KEY_NUMERIC_POUND")]
    pub const NUMERIC_POUND: Key = Key(523);
    #[doc(alias = "KEY_NUMERIC_A")]
    pub const NUMERIC_A: Key = Key(524);
    #[doc(alias = "KEY_NUMERIC_B")]
    pub const NUMERIC_B: Key = Key(525);
    #[doc(alias = "KEY_NUMERIC_C")]
    pub const NUMERIC_C: Key = Key(526);
    #[doc(alias = "KEY_NUMERIC_D")]
    pub const NUMERIC_D: Key = Key(527);
    #[doc(alias = "KEY_CAMERA_FOCUS")]
    pub const CAMERA_FOCUS: Key = Key(528);
    #[doc(alias = "KEY_WPS_BUTTON")]
    pub const WPS_BUTTON: Key = Key(529);
    #[doc(alias = "KEY_TOUCHPAD_TOGGLE")]
    pub const TOUCHPAD_TOGGLE: Key = Key(530);
    #[doc(alias = "KEY_TOUCHPAD_ON")]
    pub const TOUCHPAD_ON: Key = Key(531);
    #[doc(alias = "KEY_TOUCHPAD_OFF")]
    pub const TOUCHPAD_OFF: Key = Key(532);
    #[doc(alias = "KEY_CAMERA_ZOOMIN")]
    pub const CAMERA_ZOOMIN: Key = Key(533);
    #[doc(alias = "KEY_CAMERA_ZOOMOUT")]
    pub const CAMERA_ZOOMOUT: Key = Key(534);
    #[doc(alias = "KEY_CAMERA_UP")]
    pub const CAMERA_UP: Key = Key(535);
    #[doc(alias = "KEY_CAMERA_DOWN")]
    pub const CAMERA_DOWN: Key = Key(536);
    #[doc(alias = "KEY_CAMERA_LEFT")]
    pub const CAMERA_LEFT: Key = Key(537);
    #[doc(alias = "KEY_CAMERA_RIGHT")]
    pub const CAMERA_RIGHT: Key = Key(538);
    #[doc(alias = "KEY_ATTENDANT_ON")]
    pub const ATTENDANT_ON: Key = Key(539);
    #[doc(alias = "KEY_ATTENDANT_OFF")]
    pub const ATTENDANT_OFF: Key = Key(540);
    #[doc(alias = "KEY_ATTENDANT_TOGGLE")]
    pub const ATTENDANT_TOGGLE: Key = Key(541);
    #[doc(alias = "KEY_LIGHTS_TOGGLE")]
    pub const LIGHTS_TOGGLE: Key = Key(542);
    #[doc(alias = "KEY_ALS_TOGGLE")]
    pub const ALS_TOGGLE: Key = Key(560);
    #[doc(alias = "KEY_ROTATE_LOCK_TOGGLE")]
    pub const ROTATE_LOCK_TOGGLE: Key = Key(561);
    #[doc(alias = "KEY_BUTTONCONFIG")]
    pub const BUTTONCONFIG: Key = Key(576);
    #[doc(alias = "KEY_TASKMANAGER")]
    pub const TASKMANAGER: Key = Key(577);
    #[doc(alias = "KEY_JOURNAL")]
    pub const JOURNAL: Key = Key(578);
    #[doc(alias = "KEY_CONTROLPANEL")]
    pub const CONTROLPANEL: Key = Key(579);
    #[doc(alias = "KEY_APPSELECT")]
    pub const APPSELECT: Key = Key(580);
    #[doc(alias = "KEY_SCREENSAVER")]
    pub const SCREENSAVER: Key = Key(581);
    #[doc(alias = "KEY_VOICECOMMAND")]
    pub const VOICECOMMAND: Key = Key(582);
    #[doc(alias = "KEY_ASSISTANT")]
    pub const ASSISTANT: Key = Key(583);
    #[doc(alias = "KEY_KBD_LAYOUT_NEXT")]
    pub const KBD_LAYOUT_NEXT: Key = Key(584);
    #[doc(alias = "KEY_EMOJI_PICKER")]
    pub const EMOJI_PICKER: Key = Key(585);
    #[doc(alias = "KEY_BRIGHTNESS_MIN")]
    pub const BRIGHTNESS_MIN: Key = Key(592);
    #[doc(alias = "KEY_BRIGHTNESS_MAX")]
    pub const BRIGHTNESS_MAX: Key = Key(593);
    #[doc(alias = "KEY_KBDINPUTASSIST_PREV")]
    pub const KBDINPUTASSIST_PREV: Key = Key(608);
    #[doc(alias = "KEY_KBDINPUTASSIST_NEXT")]
    pub const KBDINPUTASSIST_NEXT: Key = Key(609);
    #[doc(alias = "KEY_KBDINPUTASSIST_PREVGROUP")]
    pub const KBDINPUTASSIST_PREVGROUP: Key = Key(610);
    #[doc(alias = "KEY_KBDINPUTASSIST_NEXTGROUP")]
    pub const KBDINPUTASSIST_NEXTGROUP: Key = Key(611);
    #[doc(alias = "KEY_KBDINPUTASSIST_ACCEPT")]
    pub const KBDINPUTASSIST_ACCEPT: Key = Key(612);
    #[doc(alias = "KEY_KBDINPUTASSIST_CANCEL")]
    pub const KBDINPUTASSIST_CANCEL: Key = Key(613);
    #[doc(alias = "KEY_RIGHT_UP")]
    pub const RIGHT_UP: Key = Key(614);
    #[doc(alias = "KEY_RIGHT_DOWN")]
    pub const RIGHT_DOWN: Key = Key(615);
    #[doc(alias = "KEY_LEFT_UP")]
    pub const LEFT_UP: Key = Key(616);
    #[doc(alias = "KEY_LEFT_DOWN")]
    pub const LEFT_DOWN: Key = Key(617);
    #[doc(alias = "KEY_ROOT_MENU")]
    pub const ROOT_MENU: Key = Key(618);
    #[doc(alias = "KEY_MEDIA_TOP_MENU")]
    pub const MEDIA_TOP_MENU: Key = Key(619);
    #[doc(alias = "KEY_NUMERIC_11")]
    pub const NUMERIC_11: Key = Key(620);
    #[doc(alias = "KEY_NUMERIC_12")]
    pub const NUMERIC_12: Key = Key(621);
    #[doc(alias = "KEY_AUDIO_DESC")]
    pub const AUDIO_DESC: Key = Key(622);
    #[doc(alias = "KEY_3D_MODE")]
    pub const _3D_MODE: Key = Key(623);
    #[doc(alias = "KEY_NEXT_FAVORITE")]
    pub const NEXT_FAVORITE: Key = Key(624);
    #[doc(alias = "KEY_STOP_RECORD")]
    pub const STOP_RECORD: Key = Key(625);
    #[doc(alias = "KEY_PAUSE_RECORD")]
    pub const PAUSE_RECORD: Key = Key(626);
    #[doc(alias = "KEY_VOD")]
    pub const VOD: Key = Key(627);
    #[doc(alias = "KEY_UNMUTE")]
    pub const UNMUTE: Key = Key(628);
    #[doc(alias = "KEY_FASTREVERSE")]
    pub const FASTREVERSE: Key = Key(629);
    #[doc(alias = "KEY_SLOWREVERSE")]
    pub const SLOWREVERSE: Key = Key(630);
    #[doc(alias = "KEY_DATA")]
    pub const DATA: Key = Key(631);
    #[doc(alias = "KEY_ONSCREEN_KEYBOARD")]
    pub const ONSCREEN_KEYBOARD: Key = Key(632);
    #[doc(alias = "KEY_PRIVACY_SCREEN_TOGGLE")]
    pub const PRIVACY_SCREEN_TOGGLE: Key = Key(633);
    #[doc(alias = "KEY_SELECTIVE_SCREENSHOT")]
    pub const SELECTIVE_SCREENSHOT: Key = Key(634);
    #[doc(alias = "KEY_MACRO1")]
    pub const MACRO1: Key = Key(656);
    #[doc(alias = "KEY_MACRO2")]
    pub const MACRO2: Key = Key(657);
    #[doc(alias = "KEY_MACRO3")]
    pub const MACRO3: Key = Key(658);
    #[doc(alias = "KEY_MACRO4")]
    pub const MACRO4: Key = Key(659);
    #[doc(alias = "KEY_MACRO5")]
    pub const MACRO5: Key = Key(660);
    #[doc(alias = "KEY_MACRO6")]
    pub const MACRO6: Key = Key(661);
    #[doc(alias = "KEY_MACRO7")]
    pub const MACRO7: Key = Key(662);
    #[doc(alias = "KEY_MACRO8")]
    pub const MACRO8: Key = Key(663);
    #[doc(alias = "KEY_MACRO9")]
    pub const MACRO9: Key = Key(664);
    #[doc(alias = "KEY_MACRO10")]
    pub const MACRO10: Key = Key(665);
    #[doc(alias = "KEY_MACRO11")]
    pub const MACRO11: Key = Key(666);
    #[doc(alias = "KEY_MACRO12")]
    pub const MACRO12: Key = Key(667);
    #[doc(alias = "KEY_MACRO13")]
    pub const MACRO13: Key = Key(668);
    #[doc(alias = "KEY_MACRO14")]
    pub const MACRO14: Key = Key(669);
    #[doc(alias = "KEY_MACRO15")]
    pub const MACRO15: Key = Key(670);
    #[doc(alias = "KEY_MACRO16")]
    pub const MACRO16: Key = Key(671);
    #[doc(alias = "KEY_MACRO17")]
    pub const MACRO17: Key = Key(672);
    #[doc(alias = "KEY_MACRO18")]
    pub const MACRO18: Key = Key(673);
    #[doc(alias = "KEY_MACRO19")]
    pub const MACRO19: Key = Key(674);
    #[doc(alias = "KEY_MACRO20")]
    pub const MACRO20: Key = Key(675);
    #[doc(alias = "KEY_MACRO21")]
    pub const MACRO21: Key = Key(676);
    #[doc(alias = "KEY_MACRO22")]
    pub const MACRO22: Key = Key(677);
    #[doc(alias = "KEY_MACRO23")]
    pub const MACRO23: Key = Key(678);
    #[doc(alias = "KEY_MACRO24")]
    pub const MACRO24: Key = Key(679);
    #[doc(alias = "KEY_MACRO25")]
    pub const MACRO25: Key = Key(680);
    #[doc(alias = "KEY_MACRO26")]
    pub const MACRO26: Key = Key(681);
    #[doc(alias = "KEY_MACRO27")]
    pub const MACRO27: Key = Key(682);
    #[doc(alias = "KEY_MACRO28")]
    pub const MACRO28: Key = Key(683);
    #[doc(alias = "KEY_MACRO29")]
    pub const MACRO29: Key = Key(684);
    #[doc(alias = "KEY_MACRO30")]
    pub const MACRO30: Key = Key(685);
    #[doc(alias = "KEY_MACRO_RECORD_START")]
    pub const MACRO_RECORD_START: Key = Key(688);
    #[doc(alias = "KEY_MACRO_RECORD_STOP")]
    pub const MACRO_RECORD_STOP: Key = Key(689);
    #[doc(alias = "KEY_MACRO_PRESET_CYCLE")]
    pub const MACRO_PRESET_CYCLE: Key = Key(690);
    #[doc(alias = "KEY_MACRO_PRESET1")]
    pub const MACRO_PRESET1: Key = Key(691);
    #[doc(alias = "KEY_MACRO_PRESET2")]
    pub const MACRO_PRESET2: Key = Key(692);
    #[doc(alias = "KEY_MACRO_PRESET3")]
    pub const MACRO_PRESET3: Key = Key(693);
    #[doc(alias = "KEY_KBD_LCD_MENU1")]
    pub const KBD_LCD_MENU1: Key = Key(696);
    #[doc(alias = "KEY_KBD_LCD_MENU2")]
    pub const KBD_LCD_MENU2: Key = Key(697);
    #[doc(alias = "KEY_KBD_LCD_MENU3")]
    pub const KBD_LCD_MENU3: Key = Key(698);
    #[doc(alias = "KEY_KBD_LCD_MENU4")]
    pub const KBD_LCD_MENU4: Key = Key(699);
    #[doc(alias = "KEY_KBD_LCD_MENU5")]
    pub const KBD_LCD_MENU5: Key = Key(700);
    #[doc(alias = "KEY_MIN_INTERESTING")]
    pub const MIN_INTERESTING: Key = Key(113);
    #[doc(alias = "KEY_MAX")]
    pub const MAX: Key = Key(767);
    #[doc(alias = "KEY_CNT")]
    pub const CNT: Key = Key(768);
}
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Led(u32);
impl Led {
    pub const fn new(value: u32) -> Led {
        Led(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Led {
    fn from(value: u32) -> Led {
        Led(value)
    }
}
impl From<Led> for u32 {
    fn from(value: Led) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Led {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Led {
    #[doc(alias = "LED_NUML")]
    pub const NUML: Led = Led(0);
    #[doc(alias = "LED_CAPSL")]
    pub const CAPSL: Led = Led(1);
    #[doc(alias = "LED_SCROLLL")]
    pub const SCROLLL: Led = Led(2);
    #[doc(alias = "LED_COMPOSE")]
    pub const COMPOSE: Led = Led(3);
    #[doc(alias = "LED_KANA")]
    pub const KANA: Led = Led(4);
    #[doc(alias = "LED_SLEEP")]
    pub const SLEEP: Led = Led(5);
    #[doc(alias = "LED_SUSPEND")]
    pub const SUSPEND: Led = Led(6);
    #[doc(alias = "LED_MUTE")]
    pub const MUTE: Led = Led(7);
    #[doc(alias = "LED_MISC")]
    pub const MISC: Led = Led(8);
    #[doc(alias = "LED_MAIL")]
    pub const MAIL: Led = Led(9);
    #[doc(alias = "LED_CHARGING")]
    pub const CHARGING: Led = Led(10);
    #[doc(alias = "LED_MAX")]
    pub const MAX: Led = Led(15);
    #[doc(alias = "LED_CNT")]
    pub const CNT: Led = Led(16);
}
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Msc(u32);
impl Msc {
    pub const fn new(value: u32) -> Msc {
        Msc(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Msc {
    fn from(value: u32) -> Msc {
        Msc(value)
    }
}
impl From<Msc> for u32 {
    fn from(value: Msc) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Msc {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Msc {
    #[doc(alias = "MSC_SERIAL")]
    pub const SERIAL: Msc = Msc(0);
    #[doc(alias = "MSC_PULSELED")]
    pub const PULSELED: Msc = Msc(1);
    #[doc(alias = "MSC_GESTURE")]
    pub const GESTURE: Msc = Msc(2);
    #[doc(alias = "MSC_RAW")]
    pub const RAW: Msc = Msc(3);
    #[doc(alias = "MSC_SCAN")]
    pub const SCAN: Msc = Msc(4);
    #[doc(alias = "MSC_TIMESTAMP")]
    pub const TIMESTAMP: Msc = Msc(5);
    #[doc(alias = "MSC_MAX")]
    pub const MAX: Msc = Msc(7);
    #[doc(alias = "MSC_CNT")]
    pub const CNT: Msc = Msc(8);
}
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Rel(u32);
impl Rel {
    pub const fn new(value: u32) -> Rel {
        Rel(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Rel {
    fn from(value: u32) -> Rel {
        Rel(value)
    }
}
impl From<Rel> for u32 {
    fn from(value: Rel) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Rel {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Rel {
    #[doc(alias = "REL_X")]
    pub const X: Rel = Rel(0);
    #[doc(alias = "REL_Y")]
    pub const Y: Rel = Rel(1);
    #[doc(alias = "REL_Z")]
    pub const Z: Rel = Rel(2);
    #[doc(alias = "REL_RX")]
    pub const RX: Rel = Rel(3);
    #[doc(alias = "REL_RY")]
    pub const RY: Rel = Rel(4);
    #[doc(alias = "REL_RZ")]
    pub const RZ: Rel = Rel(5);
    #[doc(alias = "REL_HWHEEL")]
    pub const HWHEEL: Rel = Rel(6);
    #[doc(alias = "REL_DIAL")]
    pub const DIAL: Rel = Rel(7);
    #[doc(alias = "REL_WHEEL")]
    pub const WHEEL: Rel = Rel(8);
    #[doc(alias = "REL_MISC")]
    pub const MISC: Rel = Rel(9);
    #[doc(alias = "REL_RESERVED")]
    pub const RESERVED: Rel = Rel(10);
    #[doc(alias = "REL_WHEEL_HI_RES")]
    pub const WHEEL_HI_RES: Rel = Rel(11);
    #[doc(alias = "REL_HWHEEL_HI_RES")]
    pub const HWHEEL_HI_RES: Rel = Rel(12);
    #[doc(alias = "REL_MAX")]
    pub const MAX: Rel = Rel(15);
    #[doc(alias = "REL_CNT")]
    pub const CNT: Rel = Rel(16);
}
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Rep(u32);
impl Rep {
    pub const fn new(value: u32) -> Rep {
        Rep(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Rep {
    fn from(value: u32) -> Rep {
        Rep(value)
    }
}
impl From<Rep> for u32 {
    fn from(value: Rep) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Rep {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Rep {
    #[doc(alias = "REP_DELAY")]
    pub const DELAY: Rep = Rep(0);
    #[doc(alias = "REP_PERIOD")]
    pub const PERIOD: Rep = Rep(1);
    #[doc(alias = "REP_MAX")]
    pub const MAX: Rep = Rep(1);
    #[doc(alias = "REP_CNT")]
    pub const CNT: Rep = Rep(2);
}
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Snd(u32);
impl Snd {
    pub const fn new(value: u32) -> Snd {
        Snd(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Snd {
    fn from(value: u32) -> Snd {
        Snd(value)
    }
}
impl From<Snd> for u32 {
    fn from(value: Snd) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Snd {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Snd {
    #[doc(alias = "SND_CLICK")]
    pub const CLICK: Snd = Snd(0);
    #[doc(alias = "SND_BELL")]
    pub const BELL: Snd = Snd(1);
    #[doc(alias = "SND_TONE")]
    pub const TONE: Snd = Snd(2);
    #[doc(alias = "SND_MAX")]
    pub const MAX: Snd = Snd(7);
    #[doc(alias = "SND_CNT")]
    pub const CNT: Snd = Snd(8);
}
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Sw(u32);
impl Sw {
    pub const fn new(value: u32) -> Sw {
        Sw(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Sw {
    fn from(value: u32) -> Sw {
        Sw(value)
    }
}
impl From<Sw> for u32 {
    fn from(value: Sw) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Sw {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Sw {
    #[doc(alias = "SW_LID")]
    pub const LID: Sw = Sw(0);
    #[doc(alias = "SW_TABLET_MODE")]
    pub const TABLET_MODE: Sw = Sw(1);
    #[doc(alias = "SW_HEADPHONE_INSERT")]
    pub const HEADPHONE_INSERT: Sw = Sw(2);
    #[doc(alias = "SW_RFKILL_ALL")]
    pub const RFKILL_ALL: Sw = Sw(3);
    #[doc(alias = "SW_RADIO")]
    pub const RADIO: Sw = Sw(3);
    #[doc(alias = "SW_MICROPHONE_INSERT")]
    pub const MICROPHONE_INSERT: Sw = Sw(4);
    #[doc(alias = "SW_DOCK")]
    pub const DOCK: Sw = Sw(5);
    #[doc(alias = "SW_LINEOUT_INSERT")]
    pub const LINEOUT_INSERT: Sw = Sw(6);
    #[doc(alias = "SW_JACK_PHYSICAL_INSERT")]
    pub const JACK_PHYSICAL_INSERT: Sw = Sw(7);
    #[doc(alias = "SW_VIDEOOUT_INSERT")]
    pub const VIDEOOUT_INSERT: Sw = Sw(8);
    #[doc(alias = "SW_CAMERA_LENS_COVER")]
    pub const CAMERA_LENS_COVER: Sw = Sw(9);
    #[doc(alias = "SW_KEYPAD_SLIDE")]
    pub const KEYPAD_SLIDE: Sw = Sw(10);
    #[doc(alias = "SW_FRONT_PROXIMITY")]
    pub const FRONT_PROXIMITY: Sw = Sw(11);
    #[doc(alias = "SW_ROTATE_LOCK")]
    pub const ROTATE_LOCK: Sw = Sw(12);
    #[doc(alias = "SW_LINEIN_INSERT")]
    pub const LINEIN_INSERT: Sw = Sw(13);
    #[doc(alias = "SW_MUTE_DEVICE")]
    pub const MUTE_DEVICE: Sw = Sw(14);
    #[doc(alias = "SW_PEN_INSERTED")]
    pub const PEN_INSERTED: Sw = Sw(15);
    #[doc(alias = "SW_MACHINE_COVER")]
    pub const MACHINE_COVER: Sw = Sw(16);
    #[doc(alias = "SW_MAX")]
    pub const MAX: Sw = Sw(16);
    #[doc(alias = "SW_CNT")]
    pub const CNT: Sw = Sw(17);
}
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Syn(u32);
impl Syn {
    pub const fn new(value: u32) -> Syn {
        Syn(value)
    }
    pub const fn into_inner(self) -> u32 {
        self.0
    }
}
impl From<u32> for Syn {
    fn from(value: u32) -> Syn {
        Syn(value)
    }
}
impl From<Syn> for u32 {
    fn from(value: Syn) -> u32 {
        value.0
    }
}
impl PartialEq<u32> for Syn {
    fn eq(&self, other: &u32) -> bool {
        &self.0 == other
    }
}
impl Syn {
    #[doc(alias = "SYN_REPORT")]
    pub const REPORT: Syn = Syn(0);
    #[doc(alias = "SYN_CONFIG")]
    pub const CONFIG: Syn = Syn(1);
    #[doc(alias = "SYN_MT_REPORT")]
    pub const MT_REPORT: Syn = Syn(2);
    #[doc(alias = "SYN_DROPPED")]
    pub const DROPPED: Syn = Syn(3);
    #[doc(alias = "SYN_MAX")]
    pub const MAX: Syn = Syn(15);
    #[doc(alias = "SYN_CNT")]
    pub const CNT: Syn = Syn(16);
}
