name: Continuous Integration

on:
  push:
    branches: master
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  build:
    env:
      RUSTFLAGS: "-D warnings"

    strategy:
      matrix:
        toolchain:
        - stable
        - nightly

    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt
      - name: Build (${{ matrix.toolchain }})
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

  doc:
    env:
      RUSTDOCFLAGS: "-Dwarnings"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --release
